language: C
install:
  - sudo apt-get update -qq
  - uname -m
  - sudo apt-get install -y cloog-isl mingw32
  - export MINGW=/opt/mingw32
  - export PATH=$MINGW/bin:$PATH
  - export CC=i686-w64-mingw32-gcc
  - export CXX=i686-w64-mingw32-g++

script:
  - gcc -v 
  - gcc -dumpmachine
  - make -f LCD_TCP_MINGW_DLL.cbp.mak -j2 VERBOSE=1