os: osx
language: C
install:
  - brew install mingw-w64

script:
  - chmod +x build.sh
  - ./build.sh
  - ls
notifications:
  email:
    on_success: change
    on_failure: change
before_deploy:
- zip LCD_TCP_MINGW_DLL.zip LCD_TCP_MINGW_DLL.dll
deploy:
  provider: releases
  api_key:
    secure: EyER/b6D3A3sCSpH4//S9QIBb94hEACc8sZpYokcvoAXfOYeUH/dFXIlPzYElr45x4hXp7dJWUERQj+N7eNA9BnnzFz1GgUqXBtqs7PQ4R/kL03VSMqj75x1qTfg7TUeVzIREMGQjMEChFabYMrJRDN4klSgRH9Z5XIsRHIWMir6LIL4Fva3fBHSJbemYtJpb6SsMMjPw3/lyltsr2zwgwNnxsKCWzqlRlClrkybvpub7qKPaLDmsBuLsB+4MrzcqZHC+DckTp08wH4Zyi8MzlqfvH5SakNkM9vPc4taMlIcgvIoOZdGYBHkf6jmcSRypd7H/S0kLOUTrn9m/nr2gqjnTfx46FiQoiuUVxcGXhCZmchi9yGSLrJT4SbZBTLIz0KAEwqyOK3lKCDvCPPs0AaZeTFkBwzIHN/oaIqi4wPJ/9NEvYxW6Tq9MaewCb42NSHxmxy3RNUKi2Cldw+ewCWSSmi7xf+7CyLYgEyVmfbpr0cqy2cyrR1wv2LPmA10PhfAZymc9w4/C3kQhl+h9wrN66quAuKClQnipLb65Awk4Bfs7wDlYDcbesYTBX6BIaRTg1kwdtIOUzWiQKWdhP1B1GsjYz87Ejf6mRJc1m16umkeevBawEFpNYZZGDE96H/EY1HyB1IOSPGTC7bT43HAMtPOde0j7DLXWSJrcCM=
  file: LCD_TCP_MINGW_DLL.zip
  skip_cleanup: true
  on:
    repo: eeyrw/LcdTcpDll
    tags: true