language: C
install:
  - sudo apt-get update -qq
  - uname -m
  - sudo apt-get install -y cloog-isl mingw32
  - sudo apt-get install -y mingw32-x-binutils mingw32-x-gcc mingw32-x-runtime
  - export MINGW=/opt/mingw$BITSIZE
  - export PATH=$MINGW/bin:$PATH
  - export CC=i686-w64-mingw32-gcc
  - export CXX=i686-w64-mingw32-g++

script:
  - gcc -v 
  - gcc -dumpmachine
  - make -f LCD_TCP_MINGW_DLL.cbp.mak -j2 VERBOSE=1